@startuml

class Avion{
  lista_sillas: string
  porcentaje_ocupacion: float
}

class Silla{
  numero: string
  clase: string
  posicion:string
  ocupada:boolean
  pasajero: Pasajero
}

class Pasajero{
  cedula: string
  nombres : string
}

class CasoUsoSimuladorAvion{
  respositorioAvion: RespositorioAvion
  + crear(cuenta)
  + editar(asiento,destino)
  + eliminar(pasajero)
}

Pasajero <|-- Silla
Avion <|-- Silla
CasoUsoSimuladorAvion o-- respositorioAvion
CasoUsoSimuladorAvion ..> Avion
@enduml